const FETCH_POKEMON = 'app/pokemon/FETCH_POKEMON';
const FETCH_POKEMON_SUCCESS = 'app/pokemon/FETCH_POKEMON_SUCCESS';
const FETCH_POKEMON_FAILURE = 'app/pokemon/FETCH_POKEMON_FAILURE';
const REPLACE_POKEMON = 'app/pokemon/REPLACE_POKEMON';

export default {
    FETCH_POKEMON,
    FETCH_POKEMON_SUCCESS,
    FETCH_POKEMON_FAILURE,
    REPLACE_POKEMON,
};
